version: 0

meta:
    category: "Lightning Node Management"
    name: "Lightning Terminal"
    version: "0.4.1-alpha"
    tagline: "The easiest way to manage channel liquidity"
    description: |
        Lightning Terminal is the easiest way to manage inbound and outbound
        liquidity on the Lightning Network. Keep your channels open and the funds flowing.
        It provides a visual interface for interacting with your channels and balances
        using Loop.
        
        New: Introducing Lightning Pool, a marketplace for Lightning channels.
        You can now earn sats by opening new channels to those looking to receive funds
        on Lightning for a set period of time, or rent a channel to start accepting payments
        instantly. Join the marketplace and start putting your Bitcoin to work.
        
        Why use Pool?
        - Earn a return on Lightning capital
        - Rent a channel and start accepting payments instantly
        - Open channels for less with transaction batching
        
        Why use Loop?
        - Add "inbound liquidity" to receive payments
        - Reduce transaction fees by recycling and reusing Lightning channels
        - Send funds to and from users or services that aren't yet Lightning enabled
        - Configurable wait times and \"batching\" allow for further fee savings
        - Refill and offload funds from any number of Lightning channels in a single on-chain transaction"
    developer: "Lightning Labs"
    website: "https://lightning.engineering"
    dependencies:
    - "lnd"
    repo: "https://github.com/lightninglabs/lightning-terminal"
    support: "https://github.com/lightninglabs/lightning-terminal/issues/new"
    port: 3004
    gallery:
    - "1.jpg"
    - "2.jpg"
    - "3.jpg"
    - "4.jpg"
    defaultPassword: "moneyprintergobrrr"
