#!/usr/bin/env bash

set -euo pipefail

UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../../..)"

check_root () {
  if [[ $UID != 0 ]]; then
    echo "This script must be run as root"
    exit 1
  fi
}

main () {
  check_root

  # Append iptables rule to forward port 80 to port 8000
  # The status server runs on port 8000 but this rule will route all port 80
  # HTTP traffic to it.
  # When the Umbrel service has started Docker will overwrite this rule and
  # instead forward port 80 to the Umbrel HTTP server container.
  "${UMBREL_ROOT}/scripts/umbrel-os/status-server/setup-iptables"

  # Spawn the server
  exec "${UMBREL_ROOT}/scripts/umbrel-os/status-server/status-server"
}

main
