import {useQuery, useQueryClient, type QueryClient} from '@tanstack/react-query'
import {useEffect} from 'react'

import type {FileSystemItem} from '@/features/files/types'
import {trpcReact} from '@/trpc/trpc'

const QUERY_KEY = 'files-on-demand-thumbnail'

// How many thumbnails are asked of the backend at once. A listing mounts a
// screenful of icons in one frame and a fast scroll mounts many screenfuls,
// while the backend generates missing thumbnails a few at a time — so the
// rest wait their turn here. A slot is held until the backend has answered:
// that is the load the cap is there to bound.
const CAPACITY = 4
let running = 0
const waiting: (() => void)[] = []

function acquire() {
	if (running < CAPACITY) {
		running++
		return Promise.resolve()
	}
	return new Promise<void>((resolve) => waiting.push(resolve))
}

function release() {
	// Straight to whoever is next, so the slot can't be taken in between
	const next = waiting.shift()
	if (next) next()
	else running--
}

// A thumbnail that couldn't be made is an answer too — null — but not one to
// keep: a share drops off the network, a drive is still spinning up, and the
// same ask succeeds a minute later. It is remembered for as long as the
// backend itself backs off a failed thumbnail, so rows scrolling in and out
// don't hammer a file that is truly broken, and after that the next row to
// show the file asks again. For storage that is never indexed in the
// background (external drives, network shares, app data) this is the only
// way a thumbnail ever arrives, so a failure must never be final.
const FAILURE_RETRY_MS = 60_000
// … and a refreshed listing retries them at once: that is what Files does
// when a share comes back, a watcher fires or an operation lands. Not the
// ones that failed a moment ago, though — a busy folder refreshes many times
// a second, and each pass would re-ask every broken file on screen.
const FAILURE_SETTLE_MS = 5_000
const LISTINGS = new Set(['list', 'recents', 'search'])
const connected = new WeakSet<QueryClient>()

function retryFailuresWithListings(client: QueryClient) {
	if (connected.has(client)) return
	connected.add(client)
	let scheduled = false
	client.getQueryCache().subscribe((event) => {
		if (event.type !== 'updated' || event.action.type !== 'invalidate') return
		const [procedure] = event.query.queryKey
		if (!Array.isArray(procedure) || procedure[0] !== 'files' || !LISTINGS.has(procedure[1])) return
		// One pass however many cached listings the invalidation swept over
		if (scheduled) return
		scheduled = true
		queueMicrotask(() => {
			scheduled = false
			void client.invalidateQueries({
				queryKey: [QUERY_KEY],
				predicate: ({state}) => state.data === null && Date.now() - state.dataUpdatedAt >= FAILURE_SETTLE_MS,
			})
		})
	})
}

// A file's thumbnail URL. Listings carry it for every thumbnail that already
// exists; one that doesn't is generated by asking — once: the answer is
// cached under the file's revision, so a virtualized row that scrolls away
// and back, or the same file shown in two places, doesn't ask again. The
// revision is path, modified time and size: a copy or a restore that keeps
// the old timestamp (cp -p, rsync -t, Rewind) is still a different file, and
// the old one's thumbnail — addressed by its content — is not its thumbnail.
export function useOnDemandThumbnail(item: FileSystemItem) {
	// The React client, not the vanilla one: that is HTTP-only, and a request
	// held open while a thumbnail is generated would sit in the very
	// connection pool the thumbnails themselves load through
	const {client: trpc} = trpcReact.useUtils()
	const queryClient = useQueryClient()
	useEffect(() => retryFailuresWithListings(queryClient), [queryClient])
	const {data} = useQuery({
		queryKey: [QUERY_KEY, item.path, item.modified, item.size],
		// The query's abort signal is deliberately left alone: reading it would
		// have the query cancelled the moment its last row unmounts, and an ask
		// already sent is worth finishing — the backend is making the thumbnail
		// either way, and the answer is here for when the row comes back.
		queryFn: async ({client, queryKey}) => {
			await acquire()
			try {
				// What can be dropped is an ask that hasn't been sent: if every row
				// that wanted it scrolled away while it waited, the turn is given
				// up, and the query goes back to never having been fetched
				if (!client.getQueryCache().find({queryKey, exact: true})?.getObserversCount()) {
					void client.cancelQueries({queryKey, exact: true}, {revert: true})
					return null
				}
				return (await trpc.files.getThumbnail.mutate({path: item.path})) ?? null
			} catch {
				return null
			} finally {
				release()
			}
		},
		// A file still arriving has nothing to draw from yet
		enabled: item.thumbnail === undefined && !item.isUploading,
		// A thumbnail is addressed by content, so its URL never goes stale; a
		// failure does (see FAILURE_RETRY_MS)
		staleTime: ({state}) => (state.data ? Infinity : FAILURE_RETRY_MS),
		retry: false,
		refetchOnWindowFocus: false,
	})
	return item.thumbnail ?? data ?? undefined
}
