#!/usr/bin/env python3
from pathlib import Path
import subprocess

from util.server import Server
import util.status_file as status_file

STATUS_FILE_PATH='/Users/lukechilds/umbrel-status'

def get_relative_path(path):
    script_dir = Path(__file__).resolve().parent
    return str(script_dir.joinpath(path))

def run(command):
    if not status_file.contains_errors(STATUS_FILE_PATH):
        raise Exception("Running commands is disabled if there are no status errors")
    subprocess.run(command, check=True)

def main():
    status_file.create_empty(STATUS_FILE_PATH)
    server = Server(directory=get_relative_path('static'))
    server.get('/status', lambda: status_file.parse(STATUS_FILE_PATH))
    server.post('/shutdown', lambda: run(['say', 'shutdown']))
    server.post('/restart', lambda: run(['say', 'restart']))
    server.post('/fail', lambda: run(['thiswillfail']))
    server.listen(8000)

main()
