version: "3.7"

services:
  web:
    image: ghcr.io/yzernik/agora:add_dockerfile@sha256:dac0b6ab1ba001d41dad86cf2505fc0654366ea20d824a850f59e1272f4f5cbf
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_AGORA_PORT:$APP_AGORA_PORT"
    volumes:
      - ${APP_DATA_DIR}/agora-files:/files
      - ${LND_DATA_DIR}:/lnd:ro
    user: "1000:1000"
    environment:
      # LND environment variables
      LND_RPC_AUTHORITY: "$LND_IP:$LND_GRPC_PORT"
      TLS_CERT_PATH: "/lnd/tls.cert"
      INVOICES_MACAROON_PATH: "/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"

      # App specific environment variables
      FILES_DIR: "/files"
      AGORA_PORT: $APP_AGORA_PORT

    networks:
      default:
        ipv4_address: $APP_AGORA_IP
