version: "3.7"

services:
  web:
    image: jensgertsen/sparkkiosk:v1.0.0
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 21214:21214
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      # Global
   

      # LND
      LND_GRPC_ENDPOINT: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_GRPC_CERT: "/lnd/tls.cert"
      LND_GRPC_MACAROON: "/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"

      # App
	  APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
      APP_PASSWORD: $APP_PASSWORD
      APP_DOMAIN: $APP_DOMAIN
      