#!/usr/bin/env bash

root_dir="$(readlink -f $1)"
signal_dir="$root_dir/signals"
trigger_dir="$root_dir/triggers"

fswatch -0 --event=PlatformSpecific $signal_dir | while read -d "" event; do
  signal="${event#"$signal_dir"}"
  signal="${signal#"/"}"
  trigger="$trigger_dir/$signal"

  echo "Got signal: $signal"
  if test -x "$trigger"; then
    echo "Executing trigger"
    "$trigger"
  else
    echo "No trigger found"
  fi
done
