#!/usr/bin/env bash
set -euo pipefail

# Start Umbrel

if [[ $UID != 0 ]]; then
    echo "Umbrel must be started as root"
    echo "Please re-run this script as"
    echo "  sudo ./start"
    exit 1
fi

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      echo "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

check_dependencies fswatch readlink dirname docker docker-compose rsync jq wget git

echo "Starting Umbrel..."
echo
echo "Setting environment variables..."
echo
DEVICE_IP="$(hostname -I | cut -d ' ' -f 1)"
DEVICE_HOSTNAME=$(hostname)
export DEVICE_HOST="http://${DEVICE_IP:-$DEVICE_HOSTNAME.local}"

echo "Starting karen..."
echo
./karen &
KAREN_PID=$!
echo $! > ./karen.pid

echo
echo "Starting Docker services..."
echo
docker-compose up --detach --build --remove-orphans
echo

echo "Umbrel is now accessible at"
echo "  $DEVICE_HOST"