#!/usr/bin/env bash
set -euo pipefail

# Start Umbrel

if [[ $UID != 0 ]]; then
    echo "Umbrel must be started as root"
    echo "Please re-run this script as"
    echo "  sudo ./start"
    exit 1
fi

echo "Starting Umbrel..."
echo
echo "Starting karen..."

./karen &
KAREN_PID=$!
echo $! > ./karen.pid

echo
echo "Starting Docker services..."

docker-compose up --detach --build --remove-orphans