#!/usr/bin/env bash
set -euo pipefail

# Stop Umbrel

if [[ $UID != 0 ]]; then
    echo "Umbrel must be stopped as root"
    echo "Please re-run this script as"
    echo "  sudo ./stop"
    exit 1
fi

echo "Stopping Docker services..."
echo
docker-compose down
