version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  web:
    container_name: web
    image: "bitwardenrs/server@sha256:1cc26a5754dff74dd9df95bbbb79af168cd21dfbd83f627ea72c85fa5852ef15"
    user: "1000:1000"
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 30s
    ports:
        - "$APP_BITWARDEN_RS_PORT:8080"
    volumes:
        - ${APP_DATA_DIR}/data:/data
    environment:
        ROCKET_PORT: "8080"
    networks:
      default:
        ipv4_address: $APP_BITWARDEN_RS_IP
