version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  vaultwarden:
    container_name: vaultwarden
    image: "vaultwarden/server:1.21.0@sha256:9303a3efb19f002631c7825b8db1eceb4a97bac716d391ac4b434f9aef344958"
    user: "1000:1000"
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    ports:
        - "$APP_VAULTWARDEN_PORT:$APP_VAULTWARDEN_PORT"
    volumes:
        - ${APP_DATA_DIR}/data:/data
    environment:
        ROCKET_PORT: "$APP_VAULTWARDEN_PORT"
    networks:
      default:
        ipv4_address: $APP_VAULTWARDEN_IP
