#!/usr/bin/env bash

UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
BACKUP_ID="1234567890"
BACKUP_KEY="abcdefghi"
BACKUP_FILE="${UMBREL_ROOT}/backup.tar.gz"

# Make sure an update is not in progres
if [[ -f "${UMBREL_ROOT}/statuses/backup-in-progress" ]]; then
    echo "A backup is already in progress. Exiting now."
    exit 1
fi

echo "Creating lock..."
touch "${UMBREL_ROOT}/statuses/backup-in-progress"

[[ -f "${UMBREL_ROOT}/.env" ]] && source "${UMBREL_ROOT}/.env"
BITCOIN_NETWORK=${BITCOIN_NETWORK:-mainnet}

[[ -d "${UMBREL_ROOT}/.backup" ]] && rm -rf "${UMBREL_ROOT}/.backup"

mkdir -p "${UMBREL_ROOT}/.backup"

cp --archive "${UMBREL_ROOT}/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/channel.backup" "${UMBREL_ROOT}/.backup/channel.backup"
cp --archive "${UMBREL_ROOT}/db/user.json" "${UMBREL_ROOT}/.backup/user.json"

cd "${UMBREL_ROOT}/.backup"

tar -czvf "${BACKUP_FILE}" .

BACKUP_API_URL="https://pvf3ozmmfl.execute-api.us-east-1.amazonaws.com/prod/v1/upload"

if [[ $BITCOIN_NETWORK == "testnet" ]]; then
    BACKUP_API_URL="https://as0ot0lg7h.execute-api.us-east-1.amazonaws.com/dev/v1/upload"
fi
if [[ $BITCOIN_NETWORK == "regtest" ]]; then
    BACKUP_API_URL="https://5fxwqbum7g.execute-api.us-east-1.amazonaws.com/dev/v1/upload"
fi

echo "Uploading backup..."
curl -F "file=@/${BACKUP_FILE}" "${BACKUP_API_URL}/${BACKUP_ID}"

rm -rf "${UMBREL_ROOT}/.backup"
rm -f "${BACKUP_FILE}"

echo "Removing lock..."
rm -f "${UMBREL_ROOT}/statuses/backup-in-progress"

echo "============================="
echo "===== Backup successful ====="
echo "============================="

exit 0
