#!/usr/bin/env bash

UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
DEBUG_SCRIPT="${UMBREL_ROOT}/scripts/debug"

cat <<EOF > "$UMBREL_ROOT"/statuses/debug-status.json
{"status": "processing"}
EOF

debug_result=$(${DEBUG_SCRIPT} | sed '/onion/d' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
echo "$debug_result" > "$UMBREL_ROOT"/statuses/debug-result

cat <<EOF > "$UMBREL_ROOT"/statuses/debug-status.json
{"status": "success"}
EOF

echo "Debug result file generated"