#!/usr/bin/env bash

UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

echo "Warning: external drive mount change detected, double-checking mount status..."
"${UMBREL_ROOT}/scripts/umbrel-os/external-storage/mount"
