#!/usr/bin/env bash

signal="${1}"

# Try to load Umbrel OS version info to detect Umbrel OS
[[ -f "/etc/default/umbrel" ]] && source "/etc/default/umbrel"


# Only change password on Umbrel OS
if [[ ! -z "${UMBREL_OS:-}" ]]; then
    # Script runs as root, we need to set the username
    echo ${1} | passwd umbrel --stdin
fi
