#!/usr/bin/env bash

signal="$(cat ${1})"

# Try to load Umbrel OS version info to detect Umbrel OS
[[ -f "/etc/default/umbrel" ]] && source "/etc/default/umbrel"


# Only change password on Umbrel OS and it should not be true/false or be empty/only spaces
if [[ ! -z "${UMBREL_OS:-}" ]] && [[ -z "${signal// }" ]] && [[ "${signal}" != "true" ]] && [[ "${signal}" != "false" ]]; then
    # Script runs as root, we need to set the username
    echo ${1} | passwd umbrel --stdin
fi
