version: '3'

services:
  frontend:
    image: kaybesee/lily-frontend:latest
    restart: on-failure
    stdin_open: true
    build:
      dockerfile: Dockerfile.frontend
      context: ./
    ports:
      - '42069:80'

  express:
    privileged: true
    image: kaybesee/lily-express:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/config
      - ${LND_DATA_DIR}/:/lnd:ro
      - /dev:/dev
    build:
      dockerfile: Dockerfile.express
      context: ./
    environment:
      - EXPRESS_PORT=5000
      - ELECTRUM_IP=$ELECTRUM_IP
      - ELECTRUM_PORT=$ELECTRUM_PORT
      - APP_PASSWORD=$APP_PASSWORD
      - APP_DATA_DIR=$APP_DATA_DIR
      - LND_IP=$LND_IP
      - LND_GRPC_PORT=$LND_GRPC_PORT
    ports:
      - '5000:5000'
