version: '3'

services:
  frontend:
    image: kaybesee/lily-frontend:latest
    stdin_open: true
    build:
      dockerfile: Dockerfile.frontend
      context: ./
    ports:
      - '42069:80'

  express:
    image: kaybesee/lily-express:latest
    volumes:
      - lily-data:/data
    env_file:
      - .env.production
    build:
      dockerfile: Dockerfile.express
      context: ./
    environment:
      - ELECTRUM_IP=$ELECTRUM_IP
      - ELECTRUM_PORT=$ELECTRUM_PORT
      - LND_IP=$LND_IP
      - LND_GRPC_PORT=$LND_GRPC_PORT
    ports:
      - '5000:5000'

volumes:
  lily-data:
