version: '3'

services:
  lily-wallet:
    image: kaybesee/lily-wallet:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/config
      - ${LND_DATA_DIR}/:/lnd:ro
    environment:
      - EXPRESS_PORT=42069
      - ELECTRUM_IP=$ELECTRUM_IP
      - ELECTRUM_PORT=$ELECTRUM_PORT
      - APP_PASSWORD=$APP_PASSWORD
      - APP_DATA_DIR=$APP_DATA_DIR
      - LND_IP=$LND_IP
      - LND_GRPC_PORT=$LND_GRPC_PORT
    ports:
      - '42069:42069'
