version: "3.7"

services:
  web:
    image: dennisreimann/tallycoin_connect:v1.7.3@sha256:802a53da7591473c1a8d97e145a717781c152657343498f62ef3f53e56c86c67
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_TALLYCOIN_CONNECT_PORT:$APP_TALLYCOIN_CONNECT_PORT"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
      LND_SOCKET: "$LND_IP:$LND_GRPC_PORT"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
      LND_TLSCERT_PATH: "/lnd/tls.cert"
      CONFIG_FILE: "/data/tallycoin_api.key"
      TALLYCOIN_PASSWD_CLEARTEXT: "$APP_PASSWORD"
    networks:
      default:
        ipv4_address: $APP_TALLYCOIN_CONNECT_IP
