version: "3.7"

services:
  satsale:
    image: satsale/satsale:0.2.9
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    ports:
      - 5000:5000
    environment:
      DATA_DIR: "/data"
      # Bitcoin Core connection details
      LND_DATA_DIR: $LND_DATA_DIR
      LND_HOST: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/invoice.macaroon
      TLS_FILE: /lnd/tls.cert

