version: "3.7"

services:
  web:
    image: nodered/node-red:2.0.6-12@sha256:c15bfeef73c2b348c0fb5f70d3b3013575a6ebf2af942a1d8196c7d7d842f6bb
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_NODE_RED_PORT}:${APP_NODE_RED_PORT}"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      PORT: $APP_NODE_RED_PORT
      BITCOIN_NETWORK: $BITCOIN_NETWORK
      BITCOIN_IP: $BITCOIN_IP
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      ELECTRUM_IP: $ELECTRUM_IP
      ELECTRUM_PORT: $ELECTRUM_PORT
    networks:
      default:
          ipv4_address: $APP_NODE_RED_IP
