version: "3.7"

services:
  web:
    image: nodered/node-red:2.0.6-12
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 1880:1880
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
      - ${BITCOIN_DATA_DIR}:/bitcoin:ro
    environment:
      BITCOIN_NETWORK: $BITCOIN_NETWORK
      BITCOIN_IP: $BITCOIN_IP
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      ELECTRUM_IP: $ELECTRUM_IP
      ELECTRUM_PORT: $ELECTRUM_PORT
      APP_DOMAIN: $APP_DOMAIN
