version: "3.3"
services:
  urbit-umbrel:
    build: .
    image: mopfelwinrux/urbit-umbrel:latest
    ports:
      - "34343:34343"
      - "8090:8090"
    volumes:
      - ${APP_DATA_DIR}/piers:/data/piers
      - ${APP_DATA_DIR}/keys:/data/keys
    environment:
      FLASK_APP: app
      APP_PASSWORD: $APP_PASSWORD
