version: "3.7"

services:
  server:
    image: matrixdotorg/synapse:v1.42.0@sha256:10a1dd576504af002a1107d6d1edddc5bb891ccfc404218fbd99a15531cef742
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_SYNAPSE_PORT:$APP_SYNAPSE_PORT"
    entrypoint: "bash"
    command: "-c './start.py generate && ./start.py migrate_config && exec ./start.py'"
    volumes:
      - ${APP_DATA_DIR}/data/synapse:/data
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_HTTP_PORT: "${APP_SYNAPSE_PORT}"
      SYNAPSE_SERVER_NAME: "${APP_HIDDEN_SERVICE}"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_ENABLE_REGISTRATION: "yes"
      SYNAPSE_NO_TLS: "yes"
    networks:
      default:
        ipv4_address: $APP_SYNAPSE_IP
