version: "3.7"

services:
  server:
    image: codercom/code-server:3.11.0@sha256:d712341c622b0ae896d8f5b8c02368e44e1f5a03b93cd0489f937352dfc7bab8
    restart: on-failure
    user: "1000:1000"
    ports:
      - "${APP_CODE_SERVER_PORT}:8080"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: "moneyprintergobrrr"
    networks:
      default:
        ipv4_address: $APP_CODE_SERVER_IP
