version: "3.7"

services:
  server:
    image: codercom/code-server:3.11.1@sha256:9bb2444f9d0c26765924e29155ac4a8febecb1e080f12c4e368e71dbe6a675b5
    restart: on-failure
    user: "1000:1000"
    ports:
      - "${APP_CODE_SERVER_PORT}:8080"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_CODE_SERVER_IP
