version: "3.3"
services:
  manager:
    image: mopfelwinrux/urbit-umbrel:v0.3.0@sha256:09ee4550be66894cc2b763d5cff9a4ed15b13a3c2a298519a857c6542069d8c7
    ports:
      - "${APP_URBIT_PORT}:8090"
      - "${APP_URBIT_P2P_PORT}:34343"
    volumes:
      - ${APP_DATA_DIR}/piers:/data/piers
      - ${APP_DATA_DIR}/keys:/data/keys
    environment:
      FLASK_APP: app
      APP_PASSWORD: ${APP_PASSWORD}
    networks:
      default:
        ipv4_address: $APP_URBIT_IP
