version: "3.3"
services:
  manager:
    image: mopfelwinrux/urbit-umbrel:v0.4.1@sha256:083db8cdb2109f29c65e186b47eeecdacd5d8021ce1c4593cf8a9f945f646171
    ports:
      - "${APP_URBIT_PORT}:8090"
      - "${APP_URBIT_P2P_PORT}:34343"
    volumes:
      - ${APP_DATA_DIR}/piers:/data/piers
      - ${APP_DATA_DIR}/keys:/data/keys
    environment:
      FLASK_APP: app
      APP_PASSWORD: ${APP_PASSWORD}
    networks:
      default:
        ipv4_address: $APP_URBIT_IP
