version: "3.3"
services:
  manager:
    image: mopfelwinrux/urbit-umbrel:latest@sha256:72630ed72801d615a1ef5de0bbe0234855d7434d529542b09206a72fb4a8367c
    ports:
      - "34343:34343"
      - "8090:8090"
    volumes:
      - ${APP_DATA_DIR}/piers:/data/piers
      - ${APP_DATA_DIR}/keys:/data/keys
    environment:
      FLASK_APP: app
      APP_PASSWORD: ${APP_PASSWORD}
