version: "3.3"
services:
  manager:
    image: mopfelwinrux/urbit-umbrel:latest@sha256:cda883f93fa6e56ab8082035b89bc1fbe8c01218986d5802e61e74097fdcc4f4
    ports:
      - "${APP_URBIT_PORT}:8090"
      - "${APP_URBIT_P2P_PORT}:34343"
    volumes:
      - ${APP_DATA_DIR}/piers:/data/piers
      - ${APP_DATA_DIR}/keys:/data/keys
    environment:
      FLASK_APP: app
      APP_PASSWORD: ${APP_PASSWORD}
    networks:
      default:
        ipv4_address: $APP_URBIT_IP
