version: "3.7"

services:
  web:
    image: bitcoinscala/oracle-server-ui:0.0.1-f4c297c5-SNAPSHOT
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - ORACLE_SERVER_API_URL=http://10.21.21.61:9998/
    ports:
      - 3010:3001
    networks:
      default:
        ipv4_address: 10.21.21.60
    depends_on: 
      - oracleserver
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.7.0-159-9b269f0e-SNAPSHOT
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
    expose:
      - 9998
    networks:
      default:
        ipv4_address: 10.21.21.61
    