version: "3.7"

services:
  web:
    image: bitcoinscala/oracle-server-ui:0.0.1-864a9f4a-SNAPSHOT
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_SERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
    ports:
      - "${APP_KRYSTAL_BULL_PORT}:3001"
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_IP
    depends_on: 
      - oracleserver
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.7.0-212-d9126650-SNAPSHOT
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED  
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_SERVER_IP