version: "3.7"

services:
  web:
    image: bitcoinscala/oracle-server-ui:1.9.0-9ca96ac1-SNAPSHOT@sha256:8f63ebf314c8757d531cb4238758142d1e12fd923ed43cdcbba68ef39d4cb56b
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
      - ${APP_DATA_DIR}/data/log:/log
    environment:
      LOG_PATH: "/log/"
      BITCOIN_S_HOME: "/home/bitcoin-s/.bitcoin-s/"
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_SERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      DEFAULT_UI_PASSWORD: $APP_PASSWORD
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    ports:
      - "${APP_KRYSTAL_BULL_PORT}:3001"
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_IP
    depends_on: 
      - oracleserver
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.9.0-59-faac871d-SNAPSHOT@sha256:6f5df67335e12acd2259e1e64bcaa292bb0b910d97f74f5f2a93b44823603885
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_SERVER_IP
