version: "3.7"

services:
  web:
    image: bitcoinscala/oracle-server-ui:1.9.0-c946d255-SNAPSHOT@sha256:8524db49036e35ce0da2dca515d54ed997328c3ca339d81e7782d4764c195995
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
      - ${APP_DATA_DIR}/data/log:/log
    environment:
      LOG_PATH: "/log/"
      BITCOIN_S_HOME: "/home/bitcoin-s/.bitcoin-s/"
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_SERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      DEFAULT_UI_PASSWORD: $APP_PASSWORD
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    ports:
      - "${APP_KRYSTAL_BULL_PORT}:3001"
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_IP
    depends_on: 
      - oracleserver
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.9.0-91-ddabc912-SNAPSHOT@sha256:4797299a6c6570bc50a54a82eba73724f01560093ec3c29db8ed521e8e6fd2ee
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_SERVER_IP
