version: "3.7"

services:
  web:
    image: bitcoinscala/oracle-server-ui:0.0.1-59b4b595-SNAPSHOT@sha256:04aa5ac3214acaf934cf81849758333e0eff948d9094e434001c8355084bbac6
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
      - ${APP_DATA_DIR}/data/log:/log
    environment:
      LOG_PATH: "/log/"
      BACKUP_PATH: "/home/bitcoin-s/.bitcoin-s/"
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_SERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      DEFAULT_UI_PASSWORD: $APP_PASSWORD
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    ports:
      - "${APP_KRYSTAL_BULL_PORT}:3001"
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_IP
    depends_on: 
      - oracleserver
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.8.0-172-99418c79-SNAPSHOT@sha256:36dd60f662f6b99cf0ca09353d141adcd8fb5b779ce2777885c863391df698c6
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_SERVER_IP
