version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  web:
    image: lncm/specter-desktop:v0.10.4
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 5m
    ports:
      - 25441:25441
    volumes:
      - ${APP_DATA_DIR}/.specter:/home/specter/.specter
    environment:
      # Pass any environment variables to your app for configuration in the form:
      # VARIABLE_NAME: value
      #
      # Here are all the Umbrel provided variables that you can pass through to
      # your app to connect to Bitcoin Core, LND, Electrum and Tor:
      #
      BTC_RPC_USER: $BITCOIN_RPC_USER
      BTC_RPC_PASSWORD: $BITCOIN_RPC_PASS
      BTC_RPC_HOST: $BITCOIN_IP
      BTC_RPC_PORT: $BITCOIN_RPC_PORT
      BTC_RPC_PROTOCOL: http

      # Bitcoin Core environment variables
      # $BITCOIN_NETWORK - Can be "mainnet", "testnet" or "regtest"
      # $BITCOIN_IP - Local IP of Bitcoin Core
      # $BITCOIN_P2P_PORT - P2P port
      # $BITCOIN_RPC_PORT - RPC port
      # $BITCOIN_RPC_USER - RPC username
      # $BITCOIN_RPC_PASS - RPC password
      # $BITCOIN_RPC_AUTH - RPC auth string
      #
      # LND environment variables
      # $LND_IP - Local IP of LND
      # $LND_GRPC_PORT - gRPC Port of LND
      # $LND_REST_PORT - REST Port of LND
      #
      # Electrum server environment variables
      # $ELECTRUM_IP - Local IP of Electrum server
      # $ELECTRUM_PORT - Port of Electrum server
      #
      # Tor proxy environment variables
      # $TOR_PROXY_IP - Local IP of Tor proxy
      # $TOR_PROXY_PORT - Port of Tor proxy
  # If your app has more services, like a database container, you can define those
  # services below:
  # db:
  #   image: <docker-image>:<tag>
  #   ...