version: "3.7"

services:
  web:
    image: ipfspodcasting/podcastnode:v0.5@sha256:aa56c571494323f210677ad4291ffead0fff31a1da1544766557e54b413f43d0
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - ${APP_IPFS_PODCASTING_P2P_PORT}:4001  # IPFS
      - ${APP_IPFS_PODCASTING_PORT}:8675  # Web UI
    volumes:
      - ${APP_DATA_DIR}/ipfs:/ipfs-podcasting/ipfs
      - ${APP_DATA_DIR}/cfg:/ipfs-podcasting/cfg
    networks:
      default:
        ipv4_address: $APP_IPFS_PODCASTING_IP
