version: "3.7"

services:
  jmg:
    image: manasgandy/jmg:v0.3.3
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 5002:5002
 jmwallet:
    image: manasgandy/jm:<tag>
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 28183:28183
    environment:
      # Bitcoin Core connection details
      JM_BITCOIND_HOST: $BITCOIN_IP
      JM_BITCOIND_PORT: $BITCOIN_RPC_PORT
      JM_BITCOIND_USER: $BITCOIN_RPC_USER
      JM_BITCOIND_PASS: $BITCOIN_RPC_PASS