version: "3.7"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.13.1@sha256:913721c815e9aa17b1653d384bf7f4d51f9f0e7fc4161930bc80efbae8ad1d12
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_UPTIME_KUMA_PORT}:3001
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
    networks:
      default:
        ipv4_address: $APP_UPTIME_KUMA_IP