version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  nbxplorer:
    image: "nicolasdorier/nbxplorer:2.1.46"
    user: "1000:1000"
    logging: *default-logging
    restart: always
    environment:
        NBXPLORER_NETWORK: "$BITCOIN_NETWORK"
        NBXPLORER_PORT: 32838
        NBXPLORER_BIND: 0.0.0.0
        NBXPLORER_CHAINS: "btc"
        NBXPLORER_SIGNALFILEDIR: "/datadir"
        NBXPLORER_BTCRPCURL: "http://$BITCOIN_IP:$BITCOIN_RPC_PORT"
        NBXPLORER_BTCNODEENDPOINT: $BITCOIN_IP:$BITCOIN_P2P_PORT
        NBXPLORER_BTCRPCUSER: $BITCOIN_RPC_USER
        NBXPLORER_BTCRPCPASSWORD: $BITCOIN_RPC_PASS
    volumes:
        - ${BITCOIN_DATA_DIR}:/root/.bitcoin:ro
        - ${APP_DATA_DIR}/data/nbxplorer:/datadir

  web:
    image: btcpayserver/btcpayserver:1.0.6.2
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 5m
    depends_on: [ nbxplorer, postgres ]
    entrypoint: [ "dotnet", "BTCPayServer.dll" ]
    ports: 
        - "3003:3003"
    environment:
        BTCPAY_DOCKERDEPLOYMENT: "false"
        BTCPAY_POSTGRES: "User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver$BITCOIN_NETWORK"
        BTCPAY_NETWORK: $BITCOIN_NETWORK
        BTCPAY_BIND: 0.0.0.0:3003
        BTCPAY_ROOTPATH: "/datadir"
        BTCPAY_CHAINS: "btc"
        BTCPAY_BTCEXPLORERURL: "http://nbxplorer:32838"
        BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=https://$LND_IP:$LND_GRPC_PORT/;macaroonfilepath=/root/.lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon;allowinsecure=true"
        BTCPAY_BTCEXTERNALLNDGRPC: "server=https://$LND_IP:$LND_GRPC_PORT/;macaroonfilepath=/root/.lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon;macaroondirectorypath=/root/.lnd/data/chain/bitcoin/$BITCOIN_NETWORK"
        BTCPAY_SOCKSENDPOINT: $TOR_PROXY_IP:$TOR_PROXY_PORT
    volumes:
        - ${APP_DATA_DIR}/data/btcpay:/datadir
        - ${APP_DATA_DIR}/data/nbxplorer:/root/.nbxplorer
        - ${LND_DATA_DIR}:/root/.lnd:ro

  postgres:
    image: postgres:9.6.20
    restart: on-failure
    stop_grace_period: 5m
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data

