version: "3.7"

services:
  web:
    image: ghcr.io/ibz/lightning-shell:v0.1.6-buster-slim@sha256:c6e09067d5480ac914ceada8ae3346ec2ab400cce10393a117b2bdffdc3a1b44
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_LIGHTNING_SHELL_PORT}:7681
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
        APP_PASSWORD: "${APP_PASSWORD}"
        LND_IP: "${LND_IP}"
        LND_GRPC_PORT: ${LND_GRPC_PORT}
    networks:
      default:
        ipv4_address: $APP_LIGHTNING_SHELL_IP
