version: "3.7"

services:
  web:
    image: ghcr.io/ibz/lightning-shell:v0.1.8-buster-slim@sha256:7dd518cca6b0106a0660a46f30faf8ec3afa52bca7648f6b88762fe291c82a42
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_LIGHTNING_SHELL_PORT}:7681
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
        APP_PASSWORD: "${APP_PASSWORD}"
        LND_IP: "${LND_IP}"
        LND_GRPC_PORT: ${LND_GRPC_PORT}
    networks:
      default:
        ipv4_address: $APP_LIGHTNING_SHELL_IP
