version: "3.7"

services:
  web:
    image: ghcr.io/bitfeed-project/bitfeed-client:v2.2.0@sha256:050c4e7c7744a856fbd49758db046c4dfead40d39a0719f35b3918e9f778b074
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - "api"
    environment:
      TARGET: "umbrel"
      BACKEND_HOST: "$APP_BITFEED_API_IP"
      BACKEND_PORT: "$APP_BITFEED_API_PORT"
    ports:
      - "$APP_BITFEED_PORT:80"
    networks:
      default:
        ipv4_address: $APP_BITFEED_IP

  api:
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.2.0@sha256:b04d9ef4f2c56bd25cd1cb6b33261a8716d6710d71c7e3c0388d12f2cc236e11
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: "$APP_BITFEED_API_PORT"
      BITCOIN_HOST: "$BITCOIN_IP"
      BITCOIN_ZMQ_RAWTX_PORT: "$BITCOIN_ZMQ_RAWTX_PORT"
      BITCOIN_ZMQ_RAWBLOCK_PORT: "$BITCOIN_ZMQ_RAWBLOCK_PORT"
      BITCOIN_ZMQ_SEQUENCE_PORT: "$BITCOIN_ZMQ_SEQUENCE_PORT"
      BITCOIN_RPC_PORT: "$BITCOIN_RPC_PORT"
      BITCOIN_RPC_USER: "$BITCOIN_RPC_USER"
      BITCOIN_RPC_PASS: "$BITCOIN_RPC_PASS"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      default:
        ipv4_address: $APP_BITFEED_API_IP
