version: "3.7"

services:
  web:
    image: ghcr.io/bitfeed-project/bitfeed-client:v2.3.1@sha256:969e16d07a96151c3773743eaf9da71ee601d81f5d371d7ee6b51a7b0d442e4f
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - "api"
    environment:
      TARGET: "umbrel"
      BACKEND_HOST: "$APP_BITFEED_API_IP"
      BACKEND_PORT: "$APP_BITFEED_API_PORT"
    ports:
      - "$APP_BITFEED_PORT:80"
    networks:
      default:
        ipv4_address: $APP_BITFEED_IP

  api:
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.3.1@sha256:b2bac98f3b7efabf18b04c8cc3b4297624f5fb6cbdecffba717760571aba9e5b
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 5m
    environment:
      PORT: "$APP_BITFEED_API_PORT"
      BITCOIN_HOST: "$BITCOIN_IP"
      BITCOIN_ZMQ_RAWTX_PORT: "$BITCOIN_ZMQ_RAWTX_PORT"
      BITCOIN_ZMQ_RAWBLOCK_PORT: "$BITCOIN_ZMQ_RAWBLOCK_PORT"
      BITCOIN_ZMQ_SEQUENCE_PORT: "$BITCOIN_ZMQ_SEQUENCE_PORT"
      BITCOIN_RPC_PORT: "$BITCOIN_RPC_PORT"
      BITCOIN_RPC_USER: "$BITCOIN_RPC_USER"
      BITCOIN_RPC_PASS: "$BITCOIN_RPC_PASS"
      TARGET: "umbrel"
      RPC_POOLS: "1"
      RPC_POOL_SIZE: "16"
      LOG_LEVEL: "info"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      default:
        ipv4_address: $APP_BITFEED_API_IP
