version: "3.7"

services:
  web:
    image: ghcr.io/bitfeed-project/bitfeed-client:v2.2.1@sha256:70c89d49d20ba3da21c648c259f45a4b89e06bfe1d97374a092dce6f891d03c6
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - "api"
    environment:
      TARGET: "umbrel"
      BACKEND_HOST: "$APP_BITFEED_API_IP"
      BACKEND_PORT: "$APP_BITFEED_API_PORT"
    ports:
      - "$APP_BITFEED_PORT:80"
    networks:
      default:
        ipv4_address: $APP_BITFEED_IP

  api:
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.2.1@sha256:60eae8109d3d6a377aec8a954f93b6be9ee48de717c9ab5810c2a5afcf688554
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: "$APP_BITFEED_API_PORT"
      BITCOIN_HOST: "$BITCOIN_IP"
      BITCOIN_ZMQ_RAWTX_PORT: "$BITCOIN_ZMQ_RAWTX_PORT"
      BITCOIN_ZMQ_RAWBLOCK_PORT: "$BITCOIN_ZMQ_RAWBLOCK_PORT"
      BITCOIN_ZMQ_SEQUENCE_PORT: "$BITCOIN_ZMQ_SEQUENCE_PORT"
      BITCOIN_RPC_PORT: "$BITCOIN_RPC_PORT"
      BITCOIN_RPC_USER: "$BITCOIN_RPC_USER"
      BITCOIN_RPC_PASS: "$BITCOIN_RPC_PASS"
      RPC_POOLS: "1"
      RPC_POOL_SIZE: "16"
      LOG_LEVEL: "info"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      default:
        ipv4_address: $APP_BITFEED_API_IP
