#!/usr/bin/env bash

UMBREL_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../.."
UMBREL_OS_SCRIPTS="${UMBREL_ROOT}/scripts/umbrel-os"

if [ ! -f /etc/systemd/system/umbrel.service ]; then

  echo "Umbrel systemd service not found. Looks like the first boot..."
  echo "Configuring Umbrel now..."
  echo
  if [ -f "$UMBREL_ROOT"/scripts/configure ]; then
    cd "$UMBREL_ROOT"
    ./scripts/configure || exit 1
  else 
    echo "Error: No configuration script not found at $UMBREL_ROOT/scripts/configure"
    exit 1
  fi
  echo
  echo "Configuration complete"
  echo

  echo "Setting up Umbrel systemd startup service..."

  if [ ! -f "${UMBREL_OS_SCRIPTS}/services/umbrel.service" ]; then
    echo "Error: umbrel.service not found inside ${UMBREL_OS_SCRIPTS}/services"
    exit 1
  fi

  echo "Copying umbrel.service to /etc/systemd/system/umbrel.service"
  cp "${UMBREL_OS_SCRIPTS}/services/umbrel.service" /etc/systemd/system/umbrel.service

  echo "Enabling umbrel.service..."
  systemctl enable umbrel.service

  echo "Starting umbrel.service..."
  systemctl start umbrel.service
fi

# Display connection details on the TTY
if [ -x "$(command -v umbrel-details)" ]; then
  # We run this in the background because it waits for the Tor hidden service
  # to be created on first boot. rc.local needs to exit so the boot process
  # can continue.
  umbrel-details &
fi

exit 0
