#!/usr/bin/env bash

UMBREL_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../.."
UMBREL_OS_SCRIPTS="${UMBREL_ROOT}/scripts/umbrel-os"

# Creates, enables and starts a systemd service
enable_service() {
  service="${1}"
  if [ ! -f "/etc/systemd/system/${service}" ]; then
    echo "Setting up ${service}"
    if [ ! -f "${UMBREL_OS_SCRIPTS}/services/${service}" ]; then
      echo "Error: service file not found at ${UMBREL_OS_SCRIPTS}/services/${service}"
      exit 1
    fi
    echo "Copying ${service} to /etc/systemd/system/${service}"
    cp "${UMBREL_OS_SCRIPTS}/services/${service}" "/etc/systemd/system/${service}"

    echo "Enabling ${service}..."
    systemctl enable "${service}"

    echo "Starting ${service}..."
    systemctl start "${service}"
  else
    echo "Skipping ${service}: Already exists"
  fi
}

# Configure Umbrel on first boot
# We assume that it's the first boot if 'umbrel.service' doesn't exist
if [ ! -f "/etc/systemd/system/umbrel.service" ]; then
  echo "======================================"
  echo "============ FIRST BOOT =============="
  echo "=========== hello world! ============="
  echo "======================================"
  echo 
  echo "Configuring Umbrel..."
  echo
  if [ -f "${UMBREL_ROOT}/scripts/configure" ]; then
    cd "$UMBREL_ROOT"
    NETWORK=regtest ./scripts/configure || exit 1
  else 
    echo "Error: No configuration script not found at ${UMBREL_ROOT}/scripts/configure"
    exit 1
  fi
fi

# Enable all services
enable_service "external-storage.service"
enable_service "umbrel.service"
enable_service "connection-details.service"

exit 0
