#!/usr/bin/env bash

UMBREL_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../.."
source "${UMBREL_ROOT}/scripts/monitor-lib"

# Monitor LND channel.backup
file_path="${UMBREL_ROOT}/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/channel.backup"
trigger="backup"
monitor_file ${file_path} ${trigger} &

# Monitor db/user.json
# We want to back up user settings too, however we currently store the encrypted
# mnemonic in this file which is not safe to backup remotely.
# Uncomment this in the future once we've ensured there's no critical data in
# this file.
# monitor_file "${UMBREL_ROOT}/db/user.json" &
