#!/usr/bin/env bash

set -euo pipefail

# This script will:
# - Look for an external storage device 
#   that contains an Umbrel install
# - If yes
# - - Unmount it

UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../../..)"
MOUNT_POINT="/mnt/data"
EXTERNAL_UMBREL_ROOT="${MOUNT_POINT}/umbrel"

check_root () {
  if [[ $UID != 0 ]]; then
    echo "This script must be run as root"
    exit 1
  fi
}

check_root

echo "Running external storage unmount script..."

echo "Checking if an Umbrel drive is currently mounted..."
if [[ -f "${EXTERNAL_UMBREL_ROOT}"/.umbrel ]]; then
  echo "Found an Umbrel drive"
  echo "Unmounting it now..."
  umount "$MOUNT_POINT"
else
  echo "No Umbrel drive found"
fi
