version: '3.7'

services:
  tor_proxy:
    container_name: tor_proxy
    image: ghcr.io/getumbrel/tor:0.4.9.11@sha256:e382b8629c0dfef6ceb396b062622d4e4e955b19d6f16b883fd2c0723ad5671a
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${UMBREL_TORRC}:/etc/tor/torrc:ro
      - ${UMBREL_DATA_DIR}/tor/data:/data
    environment:
      HOME: '/tmp'
    networks:
      default:
        ipv4_address: $TOR_PROXY_IP
networks:
  default:
    name: umbrel_main_network
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: '$NETWORK_IP/16'
        - subnet: '$NETWORK_IP_v6/64'