version: 0

meta:
    category: "Explorers"
    name: "BTC RPC Explorer"
    version: 3.1.1
    tagline: "Simple, database-free blockchain explorer"
    description: |
        BTC RPC Explorer is a full-featured, self-hosted explorer for the Bitcoin blockchain. With this explorer, you can explore not just the blockchain database, but also explore the functional capabilities of your Umbrel.

        It comes with a network summary dashboard, detailed view of blocks, transactions, addresses, along with analysis tools for viewing stats on miner activity, mempool summary, with fee, size, and age breakdowns. You can also search by transaction ID, block hash/height, and addresses.

        It's time to appreciate the "fullness" of your node.
    developer: "Dan Janosik"
    website: "https://explorer.btc21.org"
    dependencies:
    - "bitcoind"
    - "electrum"
    repo: "https://github.com/janoside/btc-rpc-explorer"
    support: "https://github.com/janoside/btc-rpc-explorer/discussions"
    port: 3002
