#!/usr/bin/env bash
set -euo pipefail

cat << "EOF"

                ,;###GGGGGGGGGGl#Sp
             ,##GGGlW""^'  '`""%GGGG#S,
           ,#GGG"                  "lGG#o
          #GGl^                      '$GG#
        ,#GGb       umbrelOS 1.0       \GGG,
        lGG"                            "GGG
       #GGGlGGGl##p,,p##lGGl##p,,p###ll##GGGG
      !GGGlW"""*GGGGGGG#""""WlGGGGG#W""*WGGGGS
       ""          "^          '"          ""

------------------------------------------------------
|                                                    |
|  umbrelOS 1.0 is currently only compatable with    |
|  Umbrel Home, Raspberry Pi 4 and Raspberry Pi 5.   |
|  Support for more devices is coming in April 2024. |
|                                                    |
------------------------------------------------------
EOF