#!/usr/bin/env bash
set -euo pipefail

arguments=${@:-}

# Shim to the old install script but pin to v0.5.4
curl https://raw.githubusercontent.com/getumbrel/umbrel/v0.5.4/scripts/install | bash -s -- --version v0.5.4 $arguments
