#!/usr/bin/env bash

check_root () {
  if [[ $UID != 0 ]]; then
    echo "Error: This script must be run as root."
    exit 1
  fi
}

check_if_not_already_running() {
  if ps ax | grep $0 | grep -v $$ | grep bash | grep -v grep
  then
    echo "backup monitor is already running"
    exit 1
  fi
}

check_root

check_if_not_already_running


if [[ ! -d "${UMBREL_ROOT}" ]]; then
  echo "Root dir does not exist '$UMBREL_ROOT'"
  exit 1
fi

[[ -f "${UMBREL_ROOT}/.env" ]] && source "${UMBREL_ROOT}/.env"
BITCOIN_NETWORK=${BITCOIN_NETWORK:-mainnet}
