#!/usr/bin/env bash
set -euo pipefail

# Start Umbrel

if [[ $UID != 0 ]]; then
    echo "Umbrel must be started as root"
    echo "Please re-run this script as"
    echo "  sudo . scripts/start"
    exit 1
fi

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      echo "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

check_dependencies fswatch readlink dirname docker docker-compose rsync jq wget git

echo "Starting Umbrel..."
echo

if [[ -n "$1" ]]; then
  root_dir="$(readlink -f $1)"
else
  root_dir="$(dirname $(readlink -f ${BASH_SOURCE[0]}))/.."
fi

if [[ ! -d "$root_dir" ]]; then
  echo "Root dir does not exist '$root_dir'"
  exit 1
fi

cd $root_dir

echo "Starting karen..."
echo
./karen &

echo
echo "Starting Docker services..."
echo
docker-compose up --detach --build --remove-orphans
