#!/bin/bash

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

if [ $# -eq 2 ]; then
	DEST=$1
	AMT=$2

	CMD="docker exec -it lncm_lnd_1 lncli sendpayment"
	FULLCMD="${CMD} --keysend ${DEST} ${AMT}"

	RESULT=`${FULLCMD}`

	echo $RESULT
else
	echo "usage ${0} <pubkey> <amt>"
fi

