version: "3.7"

services:
  lnmarkets:
    image: ghcr.io/ln-markets/umbrel:v1.1.4@sha256:d9168a2a3e1016b7cd302cde579ae3013aac57ebeaf89c44f5dbc02f604779cc
    init: true
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_LNMARKETS_PORT:$APP_LNMARKETS_PORT"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      BITCOIN_NETWORK: $BITCOIN_NETWORK
      APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
      APP_DOMAIN: $APP_DOMAIN
      API_PORT: $APP_LNMARKETS_PORT
    networks:
      default:
        ipv4_address: $APP_LNMARKETS_IP
