version: '3.7'

services:
  lnmarkets:
    image: ghcr.io/ln-markets/umbrel:v1.0.0@sha256:e7bfe4ae840bfddc0af398a9bc700044778d1090a7a56389265116d23dc13cab
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_LNMARKETS_PORT:$APP_LNMARKETS_PORT"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      APP_URL: 0.0.0.0
      API_PORT: $APP_LNMARKETS_PORT

      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_REST_PORT: $LND_REST_PORT

      BITCOIN_NETWORK: $BITCOIN_NETWORK
    networks:
      default:
        ipv4_address: $APP_LNMARKETS_IP
