version: "3.7"

services:
  lnmarkets:
    image: ghcr.io/ln-markets/umbrel:v1.2.3@sha256:2070b9d8e57f6eb997919e0f52b90033c7492870f0b54c88c590860a67df4704
    init: true
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_LNMARKETS_PORT:$APP_LNMARKETS_PORT"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      BITCOIN_NETWORK: $BITCOIN_NETWORK
      APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
      APP_DOMAIN: $APP_DOMAIN
      APP_PASSWORD: $APP_PASSWORD
      API_PORT: $APP_LNMARKETS_PORT
    networks:
      default:
        ipv4_address: $APP_LNMARKETS_IP
