version: '3.7'

services:
  lnmarkets:
    image: ghcr.io/lnmarkets/umbrel:v1.0.0@sha256:0b4c340f7a8b676f093904d3c3ac4ae8e82965d3a8b5b440f2c21a1b8807a4ee
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_LNMARKETS_PORT:$APP_LNMARKETS_PORT"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      APP_URL: 0.0.0.0
      API_PORT: $APP_LNMARKETS_PORT

      LND_IP: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_REST_PORT: $LND_REST_PORT

      BITCOIN_NETWORK: $BITCOIN_NETWORK
    networks:
      default:
        ipv4_address: $APP_LNMARKETS_IP
