version: "3.7"

services:
  jam:
    image: ghcr.io/joinmarket-webui/joinmarket-webui-standalone:v0.0.6-clientserver-v0.9.6@sha256:a4b9a40125585d09f61539085d85846bf26a9fde5755627b163d1a29bf8bf61c
    restart: on-failure
    stop_grace_period: 1m
    init: true
    ports:
      - "$APP_JAM_PORT:80"
    volumes:
      - ${APP_DATA_DIR}/data/joinmarket:/root/.joinmarket
    environment:
      ENSURE_WALLET: 1
      RESTORE_DEFAULT_CONFIG: 1
      APP_USER: umbrel
      APP_PASSWORD: "${APP_PASSWORD}"
      jm_tor_control_host: $TOR_PROXY_IP
      jm_tor_control_port: 29051
      jm_onion_socks5_host: $TOR_PROXY_IP
      jm_onion_socks5_port: $TOR_PROXY_PORT
      jm_socks5_host: $TOR_PROXY_IP
      jm_socks5_port: $TOR_PROXY_PORT
      jm_rpc_host: $BITCOIN_IP
      jm_rpc_port: $BITCOIN_RPC_PORT
      jm_rpc_user: $BITCOIN_RPC_USER
      jm_rpc_password: "${BITCOIN_RPC_PASS}"
      jm_rpc_wallet_file: jam_default
      jm_network: $BITCOIN_NETWORK
      jm_max_cj_fee_abs: 300000 # in sats
      jm_max_cj_fee_rel: 0.0003 # 0.03%
    networks:
      default:
        ipv4_address: $APP_JAM_IP
