version: "3.7"

services:
  web:
    image: podcastindexorg/podcasting20-boosts:v0.1.4@sha256:b00eb53b7750e5f764d562c62b320dd72ec5b387189fc3caa9d876b100f5a3a4
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - 2112:2112
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      LND_URL: "$LND_IP:$LND_GRPC_PORT"
