version: 0

meta:
    category: "Wallet Servers"
    name: "BlueWallet Lightning"
    version: 1.3.3
    tagline: "Connect BlueWallet to your Lightning node"
    description: |
        Run BlueWallet in the most private and secure way possible by removing 3rd parties and connecting it directly to your Umbrel's Lightning node.

        You can pair multiple BlueWallet accounts, so your friends and family can pair their BlueWallet with your Umbrel for a trust-minimized setup.
    developer: "BlueWallet"
    website: "https://lndhub.io"
    dependencies:
    - "lnd"
    repo: "https://github.com/BlueWallet/LndHub"
    support: "https://t.me/bluewallet"
    port: 3008
