import {UNKNOWN} from '@/constants'
import {t} from '@/utils/i18n'

export function celciusToFahrenheit(tempInCelcius?: number) {
	if (tempInCelcius === undefined) return undefined
	return Math.round((tempInCelcius * 9) / 5 + 32)
}

export function tempToColor(tempInCelcius?: number) {
	const temp = tempInCelcius
	if (temp === undefined) return '#CCCCCC'

	if (temp > 85) {
		return '#F45252'
	}
	if (temp > 75) {
		return '#F1CB6B'
	}
	if (temp > 65) {
		return '#E6E953'
	}
	if (temp > 20) {
		return '#96F16B'
	}
	return '#6BF1E9'
}

// Generated by Github Copilot
export function tempToMessage(tempInCelcius?: number) {
	if (tempInCelcius === undefined) return UNKNOWN()

	const temp = tempInCelcius

	if (temp > 85) {
		return t('temp.dangerously-hot')
	}
	if (temp > 75) {
		return t('temp.hot')
	}
	if (temp === 69) {
		return t('temp.nice')
	}
	if (temp > 40) {
		return t('temp.warm')
	}
	if (temp > 20) {
		return t('temp.normal')
	}
	if (temp < -20) return t('temp.too-cold')

	return t('temp.cool')
}
