version: "3.7"

services:
  web:
    image: ghcr.io/cryptosharks131/lndg:v1.0.4@sha256:73cfee048ec1dde6e7977cc0b9d828ecc8c0a1fa667defd66c474daad9af4a0c
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_LNDG_PORT}:${APP_LNDG_PORT}"
    volumes:
      - ${LND_DATA_DIR}:/root/.lnd:ro
      - ${APP_DATA_DIR}:/lndg/data
    command:
      - sh
      - -c
      - python initialize.py -net '${BITCOIN_NETWORK}' -server '${LND_IP}:${LND_GRPC_PORT}' -pw '${APP_PASSWORD}' -d && supervisord && python manage.py runserver 0.0.0.0:${APP_LNDG_PORT}
    networks:
      default:
        ipv4_address: ${APP_LNDG_IP}
