version: "3.7"

services:
  web:
    image: podcastindexorg/podcasting20-helipad:v0.1.8@sha256:12ea841b931cf93e80461a67f13ae44fad6741f65f396530add4015121ec4621
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - ${APP_HELIPAD_PORT}:2112
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      LND_URL: "$LND_IP:$LND_GRPC_PORT"
    networks:
      default:
        ipv4_address: $APP_HELIPAD_IP
