version: "3.7"

services:
  web:
    image: podcastindexorg/podcasting20-helipad:v0.1.9@sha256:9706dc5a337dd087b188b32685a342d5d69d154b3e0449e4623c4a4e3988dd22
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - ${APP_HELIPAD_PORT}:2112
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      LND_URL: "$LND_IP:$LND_GRPC_PORT"
    networks:
      default:
        ipv4_address: $APP_HELIPAD_IP
