version: "3.7"

services:
  server:
    image: gitea/gitea:1.15.2-rootless@sha256:6caabcf0e1a21a2d885f44c8f19693ce44ec3d443e2116f86a2937db453566a8
    user: "1000:1000"
    restart: on-failure
    ports:
      - "${APP_GITEA_PORT}:${APP_GITEA_PORT}"
      - "${APP_GITEA_SSH_PORT}:${APP_GITEA_SSH_PORT}"
    volumes:
      - ${APP_DATA_DIR}/data/gitea/data:/var/lib/gitea
      - ${APP_DATA_DIR}/data/gitea/config:/etc/gitea
    environment:
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__DOMAIN: "${APP_DOMAIN}"
      GITEA__server__HTTP_PORT: "${APP_GITEA_PORT}"
      GITEA__server__SSH_DOMAIN: "${APP_DOMAIN}"
      GITEA__server__SSH_PORT: "${APP_GITEA_SSH_PORT}"
      GITEA__server__SSH_LISTEN_PORT: "${APP_GITEA_SSH_PORT}"
      GITEA__server__START_SSH_SERVER: "true"
      GITEA__database__DB_TYPE: "mysql"
      GITEA__database__HOST: "${APP_GITEA_DB_IP}:3306"
      GITEA__database__NAME: "gitea"
      GITEA__database__USER: "gitea"
      GITEA__database__PASSWD: "moneyprintergobrrr"
    networks:
      default:
        ipv4_address: $APP_GITEA_IP
  db:
    image: mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "gitea"
      MYSQL_USER: "gitea"
      MYSQL_PASSWORD: "moneyprintergobrrr"
      MYSQL_DATABASE: "gitea"
    networks:
      default:
        ipv4_address: $APP_GITEA_DB_IP
