import {createHash} from 'node:crypto'
import nodePath from 'node:path'

import fse from 'fs-extra'
import {$} from 'execa'
import PQueue from 'p-queue'

import randomToken from '../utilities/random-token.js'

import type Umbreld from '../../index.js'
import type {FileChangeEvent} from './watcher.js'
import {OWNER_USER_ID} from '../user/constants.js'
import AsyncBurstCache from '../utilities/async-burst-cache.js'
import AppDirectoryMonitor from './app-directory-monitor.js'

const WATCHER_SNAPSHOT_TTL_MS = 1000
const OWNER_SAMBA_USERNAME = 'umbrel'
const MANAGED_MEMBER_USERNAME_PREFIX = 'umbrel-smb-'
const USERNAME_MAP_PATH = '/etc/samba/username.map'

type SambaShare = {
	name: string
	path: string
	userId: string
}

type ResolvedSambaShare = SambaShare & {sharename: string}

// Global Samba config
const SMB_CONFIG = `# Generated by umbreld

[global]
# In standalone operation, a client must first "log-on" with a valid username
# and password stored on this machine.
server role = standalone

# The name of the Samba server that will show in clients.
server string = Umbrel

# Defer to mDNS for discovery instead of advertising uppercase NETBIOS name.
mdns name = mdns

# Map immutable member ids shown to clients onto private, managed Unix users.
username map = ${USERNAME_MAP_PATH}

# Use Systemd for logging.
# Samba still tries to log to file, so pipe that to /dev/null.
logging = systemd
log file = /dev/null

# Make sure that we are not leaking information to guests or anonymous users.
access based share enum = yes
restrict anonymous = 2
map to guest = never

# Better compatibility for macOS clients
# https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X
vfs objects = catia fruit streams_xattr
fruit:metadata = stream
fruit:model = MacSamba
fruit:veto_appledouble = no
fruit:nfs_aces = no
fruit:wipe_intentionally_left_blank_rfork = yes
fruit:delete_empty_adfiles = yes
fruit:posix_rename = yes

# Disable printing services.
load printers = no
disable spoolss = yes
`

// Individual share config
const shareConfig = (name: string, path: string, validUser: string) => `
# Share specific config
[${name}]
path = ${path}
writeable = yes

# Only allow the Umbrel account that created this share to access it.
valid users = ${validUser}

# Handle permissions
# We force root so samba can read files that could be created by app processes
# running as various users including root.
# We inherit owner to avoid breaking permissions for apps that expect files in
# their data directories to be owned by them.
force user = root
force group = umbrel
inherit owner = yes

# Enable Time Machine backups.
fruit:time machine = yes
`

export default class Samba {
	#umbreld: Umbreld
	logger: Umbreld['logger']
	#removeFileChangeListener?: () => void
	#appDirectories: AppDirectoryMonitor
	#removeExternalStorageChangeListener?: () => void
	#watcherShares: AsyncBurstCache<SambaShare[]>
	#credentialQueue = new PQueue({concurrency: 1})
	#shareQueue = new PQueue({concurrency: 1})

	constructor(umbreld: Umbreld) {
		this.#umbreld = umbreld
		this.#watcherShares = new AsyncBurstCache(() => this.#get(), WATCHER_SNAPSHOT_TTL_MS)
		const {name} = this.constructor
		this.logger = umbreld.logger.createChildLogger(`files:${name.toLocaleLowerCase()}`)
		this.#appDirectories = new AppDirectoryMonitor({
			listPaths: async () => (await this.#get()).map(({path}) => path),
			systemPath: (path) => umbreld.files.virtualToSystemPathUnsafe(path),
			onDelete: (path) => this.removeSharesWithin(path),
			logger: this.logger,
		})
	}

	async start() {
		this.logger.log('Starting samba')

		// Recreate local identities and passdb entries after an OS update, and
		// remove any managed identities that no longer correspond to an enabled
		// member. Share application is attempted even if credential repair fails.
		await this.applyCredentials().catch((error) => {
			this.logger.error('Failed to apply Samba credentials', error)
		})
		await this.applyShares().catch((error) => {
			this.logger.error('Failed to apply shares', error)
		})

		this.#removeFileChangeListener = this.#umbreld.eventBus.on(
			'files:watcher:change',
			this.#handleFileChange.bind(this),
		)

		this.#removeExternalStorageChangeListener = this.#umbreld.eventBus.on('files:external-storage:change', () => {
			this.applyShares().catch((error) => this.logger.error('Failed to reapply shares', error))
		})
		await this.#appDirectories.start()
	}

	async stop() {
		this.logger.log('Stopping samba')
		this.#removeFileChangeListener?.()
		await this.#appDirectories.stop()
		this.#removeExternalStorageChangeListener?.()
		await $`systemctl stop smbd`.catch((error) => this.logger.error('Failed to stop samba', error))
		await $`systemctl stop wsdd2`.catch((error) => this.logger.error('Failed to stop wsdd2', error))
	}

	#ownerSharePasswordFile() {
		return `${this.#umbreld.dataDirectory}/secrets/share-password`
	}

	// Get the password belonging to one Umbrel account. The owner's existing
	// secret file is retained for backwards compatibility; member secrets live
	// in their account records so their presence can also represent the toggle.
	async getSharePassword(userId: string = OWNER_USER_ID) {
		if (userId !== OWNER_USER_ID) {
			const member = await this.#umbreld.user.getMember(userId)
			if (!member?.sambaPassword) throw new Error('[samba-access-disabled]')
			return member.sambaPassword
		}

		const sharePasswordFile = this.#ownerSharePasswordFile()
		const sharePassword = await fse.readFile(sharePasswordFile, 'utf8').catch(async () => {
			this.logger.log('Creating share password on first run')
			const sharePassword = randomToken(128)
			await fse.outputFile(sharePasswordFile, sharePassword, {mode: 0o600})
			return sharePassword
		})
		await fse.chmod(sharePasswordFile, 0o600)
		return sharePassword
	}

	getShareUsername(userId: string = OWNER_USER_ID) {
		if (userId === OWNER_USER_ID) return OWNER_SAMBA_USERNAME

		const username = userId.toLowerCase()
		// Keep member aliases distinct from the historic owner login and the
		// private Unix usernames on the left-hand side of username.map.
		if (username === OWNER_SAMBA_USERNAME || username.startsWith(MANAGED_MEMBER_USERNAME_PREFIX)) {
			return `member-${username}`
		}
		return username
	}

	async setSharePassword(userId: string, password: string) {
		if (password.length < 6 || password.length > 127 || /[\r\n\0]/.test(password)) {
			throw new Error('[invalid-samba-password]')
		}

		if (userId === OWNER_USER_ID) {
			await fse.outputFile(this.#ownerSharePasswordFile(), password, {mode: 0o600})
		} else {
			let found = false
			await this.#umbreld.store.getWriteLock(async ({get, set}) => {
				const memberRecords = (await get('members')) ?? []
				const updatedMembers = memberRecords.map((member) => {
					if (member.id !== userId || 'deleted' in member) return member
					found = true
					if (!member.sambaPassword) throw new Error('[samba-access-disabled]')
					return {...member, sambaPassword: password}
				})
				if (found) await set('members', updatedMembers)
			})
			if (!found) throw new Error('User not found')
		}

		const failures: unknown[] = []
		await this.applyCredentials().catch((error) => failures.push(error))
		await this.disconnectUser(userId).catch((error) => failures.push(error))
		if (failures.length === 1) throw failures[0]
		if (failures.length > 1) throw new AggregateError(failures, 'Failed to rotate Samba password')
		return true
	}

	async listMemberAccess() {
		return (await this.#umbreld.user.listMembers()).map((member) => ({
			userId: member.id,
			enabled: Boolean(member.sambaPassword),
			username: this.getShareUsername(member.id),
		}))
	}

	async setMemberAccess(userId: string, enabled: boolean) {
		if (userId === OWNER_USER_ID) throw new Error('The owner always has Samba access')

		let found = false
		let revokedShares: SambaShare[] = []
		let previousShares: SambaShare[] = []
		await this.#umbreld.store.getWriteLock(async ({get, set}) => {
			const memberRecords = (await get('members')) ?? []
			const updatedMembers = memberRecords.map((member) => {
				if (member.id !== userId || 'deleted' in member) return member
				found = true
				if (enabled) return member.sambaPassword ? member : {...member, sambaPassword: randomToken(128)}

				const updatedMember = {...member}
				delete updatedMember.sambaPassword
				return updatedMember
			})
			if (!found) return

			if (!enabled) {
				const shares = this.#normalizeShares((await get('files.shares')) ?? [])
				previousShares = shares
				revokedShares = shares.filter((share) => share.userId === userId)
				await set(
					'files.shares',
					shares.filter((share) => share.userId !== userId),
				)
			}
			// Remove shares before the credential. If the process is interrupted
			// between these two durable writes, the safe residual state is an
			// account with no exports rather than exports that can reappear later.
			await set('members', updatedMembers)
		})
		if (!found) throw new Error('User not found')
		this.#watcherShares.clear()

		const failures: unknown[] = []
		if (!enabled) {
			await this.#closeShares(revokedShares, previousShares)
			await this.disconnectUser(userId).catch((error) => failures.push(error))
		}
		await this.#reconcileCredentialsAndShares().catch((error) => failures.push(error))
		if (failures.length === 1) throw failures[0]
		if (failures.length > 1)
			throw new AggregateError(failures, `Failed to ${enabled ? 'enable' : 'disable'} Samba access`)
		return {userId, enabled, username: this.getShareUsername(userId)}
	}

	// Reconcile the Unix accounts, Samba passdb, and username map that back the
	// owner plus every enabled member account.
	async applyCredentials() {
		return this.#credentialQueue.add(() => this.#applyCredentials())
	}

	async #applyCredentials() {
		const members = (await this.#umbreld.user.listMembers()).filter((member) => member.sambaPassword)
		const expectedMemberUsernames = new Set(members.map(({id}) => this.#systemUsername(id)))

		await fse.outputFile(
			USERNAME_MAP_PATH,
			members.map(({id}) => `${this.#systemUsername(id)} = ${this.getShareUsername(id)}`).join('\n') +
				(members.length ? '\n' : ''),
			{mode: 0o600},
		)
		await fse.chmod(USERNAME_MAP_PATH, 0o600)

		const systemUsers = await this.#systemUsers()
		const passdbUsers = await this.#passdbUsers()
		const failures: unknown[] = []
		await this.#applyPassword(OWNER_SAMBA_USERNAME, await this.getSharePassword()).catch((error) =>
			failures.push(error),
		)

		for (const member of members) {
			const systemUsername = this.#systemUsername(member.id)
			try {
				if (!systemUsers.has(systemUsername)) {
					await $`useradd --system --no-create-home --shell /usr/sbin/nologin --gid umbrel ${systemUsername}`
					systemUsers.add(systemUsername)
				}
				await this.#applyPassword(systemUsername, member.sambaPassword!)
			} catch (error) {
				failures.push(error)
			}
		}

		for (const systemUsername of new Set([...systemUsers, ...passdbUsers])) {
			if (!systemUsername.startsWith(MANAGED_MEMBER_USERNAME_PREFIX)) continue
			if (expectedMemberUsernames.has(systemUsername)) continue
			const cleanup = systemUsers.has(systemUsername)
				? this.#removeSystemCredential(systemUsername)
				: this.#removePassdbCredential(systemUsername)
			await cleanup.catch((error) => failures.push(error))
		}

		if (failures.length === 1) throw failures[0]
		if (failures.length > 1) throw new AggregateError(failures, 'Failed to reconcile Samba credentials')
	}

	// Compatibility alias for callers that only need to refresh the historic
	// owner credential.
	async applySharePassword() {
		return this.applyCredentials()
	}

	async #applyPassword(systemUsername: string, password: string) {
		await $({input: `${password}\n${password}\n`})`smbpasswd -s -a ${systemUsername}`
	}

	#systemUsername(userId: string) {
		if (userId === OWNER_USER_ID) return OWNER_SAMBA_USERNAME
		const digest = createHash('sha256').update(userId).digest('hex').slice(0, 20)
		return `${MANAGED_MEMBER_USERNAME_PREFIX}${digest}`
	}

	async #systemUsers() {
		const passwd = await fse.readFile('/etc/passwd', 'utf8')
		return new Set(
			passwd
				.split('\n')
				.map((line) => line.split(':', 1)[0])
				.filter(Boolean),
		)
	}

	async #passdbUsers() {
		const result = await $({reject: false})`pdbedit -L`
		if (result.exitCode !== 0) throw new Error(`Failed to list Samba users: ${result.stderr}`)
		return new Set(
			result.stdout
				.split('\n')
				.map((line) => line.split(':', 1)[0])
				.filter(Boolean),
		)
	}

	async #removeSystemCredential(systemUsername: string) {
		await this.#disconnectSystemUser(systemUsername)
		await this.#removePassdbCredential(systemUsername)
		await $`userdel ${systemUsername}`
	}

	async #removePassdbCredential(systemUsername: string) {
		// A missing passdb entry is already the desired state. `smbpasswd -x`
		// reports that as a non-zero exit. Verify the resulting state so a real
		// passdb failure is not mistaken for successful idempotent cleanup.
		const result = await $({reject: false})`smbpasswd -x ${systemUsername}`
		if (result.exitCode !== 0 && (await this.#passdbUsers()).has(systemUsername)) {
			throw new Error(`Failed to remove Samba user ${systemUsername}: ${result.stderr}`)
		}
	}

	// Public for lifecycle orchestration and fault-injection tests; callers use an
	// Umbrel account id while the private helper operates on the managed identity.
	async disconnectUser(userId: string) {
		return this.#disconnectSystemUser(this.#systemUsername(userId))
	}

	// Samba keeps authenticated sessions alive across password and config
	// changes. Disable/delete therefore terminates only the smbd workers that
	// currently serve the revoked account.
	async #disconnectSystemUser(systemUsername: string) {
		let status: Awaited<ReturnType<typeof $>>
		try {
			status = await $`smbstatus -b -u ${systemUsername}`
		} catch (error) {
			// smbstatus and smbd ship in the same Samba package. If the executable is
			// absent (as in unit-test/dev hosts), there cannot be a managed daemon to
			// revoke. Other enumeration failures fall back to restarting the daemon so
			// we never silently leave an authenticated root-forced session alive.
			if ((error as NodeJS.ErrnoException).code === 'ENOENT') return
			await this.#restartSambaForRevocation(error)
			return
		}
		const processIds = new Set(
			status.stdout
				.split('\n')
				.map((line) => line.trim().split(/\s+/, 1)[0])
				.filter((value) => /^\d+$/.test(value)),
		)
		const failures: unknown[] = []
		for (const processId of processIds) {
			try {
				// smbstatus returns the smbd worker serving this authenticated
				// connection. Samba recommends SIGTERM for a graceful worker shutdown;
				// there is no supported `smbcontrol shutdown` message.
				process.kill(Number(processId), 'SIGTERM')
			} catch (error) {
				// The worker may have exited naturally after smbstatus took its
				// snapshot, which is already the desired result.
				if ((error as NodeJS.ErrnoException).code !== 'ESRCH') failures.push(error)
			}
		}
		if (failures.length) await this.#restartSambaForRevocation(new AggregateError(failures))
	}

	async #restartSambaForRevocation(cause: unknown) {
		this.logger.error('Failed to target a Samba session; restarting smbd to guarantee revocation', cause)
		try {
			await $`systemctl restart smbd`
		} catch (restartError) {
			throw new AggregateError([cause, restartError], 'Failed to revoke active Samba sessions')
		}
	}

	#shareIdentity(share: SambaShare) {
		return `${share.userId}\0${share.path}\0${share.name}`
	}

	async #closeShares(shares: SambaShare[], universe: SambaShare[] = shares) {
		const targets = new Set(shares.map((share) => this.#shareIdentity(share)))
		const resolvedShares = (await this.#resolveSharenames(universe)).filter((share) =>
			targets.has(this.#shareIdentity(share)),
		)
		await this.#closeResolvedShares(resolvedShares)
	}

	async #closeResolvedShares(shares: ResolvedSambaShare[]) {
		for (const share of shares) {
			await $`smbcontrol smbd close-share ${share.sharename}`.catch((error) => {
				this.logger.error(`Failed to close share '${share.sharename}'`, error)
			})
		}
	}

	async #reconcileCredentialsAndShares() {
		const failures: unknown[] = []
		// Samba must see the new passdb entry and username mapping before its
		// configuration is reloaded. Keep applying shares if credential repair
		// fails so revocations can still remove exports from the live daemon.
		await this.applyCredentials().catch((error) => failures.push(error))
		await this.applyShares().catch((error) => failures.push(error))
		if (failures.length === 1) throw failures[0]
		if (failures.length > 1) throw new AggregateError(failures, 'Failed to reconcile Samba access')
	}

	async applyShares({excludePaths}: {excludePaths?: string[]} = {}) {
		return this.#shareQueue.add(() => this.#applyShares({excludePaths}))
	}

	async #applyShares({excludePaths}: {excludePaths?: string[]} = {}) {
		const shares = await this.#get()
		const enabledMemberIds = new Set(
			(await this.#umbreld.user.listMembers()).filter((member) => member.sambaPassword).map(({id}) => id),
		)

		let config = SMB_CONFIG
		let activeShares = 0
		const resolvedShares = await this.#resolveSharenames(shares)
		const eligibleShares: {share: ResolvedSambaShare; systemPath: string}[] = []

		for (const [index, share] of shares.entries()) {
			// A disabled, deleted, or tombstoned member must never be restored from a
			// stale share record, including during the startup cleanup window.
			if (share.userId !== OWNER_USER_ID && !enabledMemberIds.has(share.userId)) continue
			// smb.conf is line-oriented. Never render a legacy/corrupt record that
			// could inject another directive through its stored path or name.
			if (/[\r\n\0%]/.test(share.path) || /[\r\n\0]/.test(share.name)) continue

			const systemPath = await this.#umbreld.files.virtualToSystemPath(share.path, share.userId).catch(() => undefined)
			if (!systemPath || !(await fse.pathExists(systemPath))) continue
			eligibleShares.push({share: resolvedShares[index]!, systemPath})
		}

		const sharesToClose: ResolvedSambaShare[] = []
		for (const {share, systemPath} of eligibleShares) {
			if (excludePaths?.some((path) => share.path === path || share.path.startsWith(path + '/'))) {
				sharesToClose.push(share)
				continue
			}

			config += shareConfig(share.sharename, systemPath, this.#systemUsername(share.userId))
			activeShares++
		}

		await this.#closeResolvedShares(sharesToClose)
		await fse.writeFile('/etc/samba/smb.conf', config)

		if (activeShares === 0) return await $`systemctl stop smbd`

		await $`systemctl start smbd`
		await $`smbcontrol smbd reload-config`
		await $`systemctl start wsdd2`
	}

	async #preferredSharename(name: string, path: string, userId: string) {
		let sharename = `${name} (Umbrel)`
		const isHome = path === (userId === OWNER_USER_ID ? '/Home' : `/Users/${userId}`)
		if (isHome) {
			const account =
				userId === OWNER_USER_ID ? await this.#umbreld.user.get() : await this.#umbreld.user.getMember(userId)
			if (account?.name) {
				sharename = `${account.name}'s Umbrel`
			}
		}
		// Section names are delimited by square brackets in smb.conf. Display
		// names and directory basenames are user-controlled, so neutralize both
		// delimiters and line breaks before writing them into the config.
		sharename = sharename.replace(/[\r\n\0\[\]]/g, ' ').trim() || 'Umbrel share'
		// Preserve the owner's historic names while placing every member share in
		// a namespace whose final component cannot equal the owner's `(Umbrel)`
		// suffix. Immutable member ids keep other accounts' mount names stable even
		// when this member renames themselves or exports a similarly named folder.
		return userId === OWNER_USER_ID ? sharename : `${sharename} (User ${userId})`
	}

	async #resolveSharenames(shares: SambaShare[]): Promise<ResolvedSambaShare[]> {
		const sharenames = await Promise.all(
			shares.map((share) => this.#preferredSharename(share.name, share.path, share.userId)),
		)
		const comparisonKey = (name: string) => name.trim().replace(/\s+/g, ' ').toLocaleLowerCase()
		const identityOccurrences = new Map<string, number>()
		const disambiguationKeys = shares.map((share) => {
			const identity = this.#shareIdentity(share)
			const duplicateOrdinal = identityOccurrences.get(identity) ?? 0
			identityOccurrences.set(identity, duplicateOrdinal + 1)
			// Valid writes prevent duplicate account/path records. Retain a local
			// ordinal only so corrupt legacy duplicates can still be rendered safely.
			return duplicateOrdinal === 0 ? identity : `${identity}\0duplicate:${duplicateOrdinal}`
		})

		// Samba section names are case-insensitive, and sanitization can make two
		// distinct display names equal. Disambiguate every member of a collision
		// with a stable identity-derived suffix, then repeat in case a crafted name
		// already resembles a suffixed candidate.
		for (;;) {
			const groups = new Map<string, number[]>()
			for (const [index, sharename] of sharenames.entries()) {
				const key = comparisonKey(sharename)
				groups.set(key, [...(groups.get(key) ?? []), index])
			}
			const collisions = [...groups.values()].filter((indices) => indices.length > 1)
			if (collisions.length === 0) break
			for (const indices of collisions) {
				for (const index of indices) {
					const suffix = createHash('sha256').update(disambiguationKeys[index]!).digest('hex').slice(0, 12)
					sharenames[index] = `${sharenames[index]} (${suffix})`
				}
			}
		}

		return shares.map((share, index) => ({...share, sharename: sharenames[index]!}))
	}

	#normalizeShares(shares: {name: string; path: string; userId?: string}[]) {
		return shares.map((share) => ({...share, userId: share.userId ?? OWNER_USER_ID})) satisfies SambaShare[]
	}

	async #get() {
		return this.#normalizeShares((await this.#umbreld.store.get('files.shares')) ?? [])
	}

	async #assertAccess(userId: string) {
		if (userId === OWNER_USER_ID) return
		const member = await this.#umbreld.user.getMember(userId)
		if (!member?.sambaPassword) throw new Error('[samba-access-disabled]')
	}

	async #handleFileChange(event: FileChangeEvent) {
		if (event.type !== 'delete') return
		const shares = await this.#watcherShares.get()
		const virtualDeletedPath = this.#umbreld.files.systemToVirtualPath(event.path)
		const deletedShares = shares.filter(
			(share) => share.path === virtualDeletedPath || share.path.startsWith(virtualDeletedPath + '/'),
		)
		if (deletedShares.length > 0) await this.removeSharesWithin(virtualDeletedPath)
	}

	async listShares(userId: string = OWNER_USER_ID) {
		await this.#assertAccess(userId)
		const shares = (await this.#resolveSharenames(await this.#get())).filter((share) => share.userId === userId)
		return Promise.all(
			shares.map(async (share) => {
				const systemPath = await this.#umbreld.files
					.virtualToSystemPath(share.path, share.userId)
					.catch(() => undefined)
				return {
					name: share.name,
					path: share.path,
					available: systemPath ? await fse.pathExists(systemPath) : false,
					sharename: share.sharename,
				}
			}),
		)
	}

	async addShare(virtualPath: string, userId: string = OWNER_USER_ID) {
		await this.#assertAccess(userId)
		virtualPath = this.#umbreld.files.normalizeVirtualPath(virtualPath)
		// Samba expands `%u`, `%H`, and other substitutions on the right-hand
		// side of `path =`. A literal percent in an exported path could therefore
		// redirect a share outside the directory that was authorized here.
		if (/[\r\n\0%]/.test(virtualPath)) throw new Error('[operation-not-allowed]')
		const allowedOperations = await this.#umbreld.files.getAllowedOperations(virtualPath, userId)
		if (!allowedOperations.includes('share')) throw new Error('[operation-not-allowed]')
		// This explicit ownership check is defense in depth against future changes
		// to advisory Files operations or owner-granted path permissions.
		if (userId !== OWNER_USER_ID && this.#umbreld.files.ownerOfPath(virtualPath) !== userId) {
			throw new Error('[operation-not-allowed]')
		}
		await this.#umbreld.files.virtualToSystemPath(virtualPath, userId)

		this.logger.log(`Adding share for ${virtualPath} owned by ${userId}`)
		await this.#umbreld.store.getWriteLock(async ({get, set}) => {
			// Recheck access under the same lock as the insert. Otherwise a share
			// request that started just before disable/delete could persist a stale
			// record after revocation and resurrect it on a later re-enable.
			if (userId !== OWNER_USER_ID) {
				const members = (await get('members')) ?? []
				const member = members.find((member) => member.id === userId)
				if (!member || 'deleted' in member || !member.sambaPassword) throw new Error('[samba-access-disabled]')
			}

			const shares = this.#normalizeShares((await get('files.shares')) ?? [])
			if (shares.some((share) => share.path === virtualPath && share.userId === userId)) {
				throw new Error('[share-already-exists]')
			}

			const basename = nodePath.basename(virtualPath)
			let name = basename
			let suffix = 1
			while (shares.some((share) => share.name.toLocaleLowerCase() === name.toLocaleLowerCase())) {
				suffix++
				name = `${basename} (${suffix})`
			}
			await set('files.shares', [...shares, {name, path: virtualPath, userId}])
		})
		this.#watcherShares.clear()
		await this.applyShares()
		this.#appDirectories.forget(virtualPath)
		await this.#appDirectories.refresh()
		return virtualPath
	}

	async removeShare(virtualPath: string, userId: string = OWNER_USER_ID) {
		await this.#assertAccess(userId)
		virtualPath = this.#umbreld.files.normalizeVirtualPath(virtualPath)
		this.logger.log(`Removing share for ${virtualPath} owned by ${userId}`)

		let deleted = false
		await this.#umbreld.store.getWriteLock(async ({get, set}) => {
			const shares = this.#normalizeShares((await get('files.shares')) ?? [])
			const remaining = shares.filter((share) => share.path !== virtualPath || share.userId !== userId)
			deleted = remaining.length < shares.length
			if (deleted) await set('files.shares', remaining)
		})
		this.#watcherShares.clear()

		// Preserve Samba's normal session behavior for an ordinary unshare to
		// avoid corrupting in-flight writes. Disable/delete use the stronger path.
		if (deleted) await this.applyShares()
		return deleted
	}

	async removeSharesWithin(virtualPath: string) {
		virtualPath = this.#umbreld.files.normalizeVirtualPath(virtualPath)
		let deleted = false
		await this.#umbreld.store.getWriteLock(async ({get, set}) => {
			const shares = this.#normalizeShares((await get('files.shares')) ?? [])
			const remaining = shares.filter(
				(share) => share.path !== virtualPath && !share.path.startsWith(`${virtualPath}/`),
			)
			deleted = remaining.length < shares.length
			if (deleted) await set('files.shares', remaining)
		})
		this.#watcherShares.clear()
		if (deleted) await this.applyShares()
		return deleted
	}

	// Idempotent member deletion cleanup. This always reapplies credentials and
	// config so a retry can converge after a prior partial system failure.
	async removeUser(userId: string) {
		if (userId === OWNER_USER_ID) throw new Error('The owner account cannot be removed from Samba')
		let revokedShares: SambaShare[] = []
		let previousShares: SambaShare[] = []
		await this.#umbreld.store.getWriteLock(async ({get, set}) => {
			const shares = this.#normalizeShares((await get('files.shares')) ?? [])
			previousShares = shares
			revokedShares = shares.filter((share) => share.userId === userId)
			if (revokedShares.length) {
				await set(
					'files.shares',
					shares.filter((share) => share.userId !== userId),
				)
			}
		})
		this.#watcherShares.clear()
		await this.#closeShares(revokedShares, previousShares)
		const failures: unknown[] = []
		await this.disconnectUser(userId).catch((error) => failures.push(error))
		await this.#reconcileCredentialsAndShares().catch((error) => failures.push(error))
		if (failures.length === 1) throw failures[0]
		if (failures.length > 1) throw new AggregateError(failures, `Failed to remove Samba user ${userId}`)
		return revokedShares.length > 0
	}
}
